### ISSUE TITLE
Can we really upload the papers here publicly?

### ISSUE THREAD

**Issue by nisargjhaveri** [IREL-IIITH/IREL-Reading-Group#1]
This repo is licenced as GPL 3.0. Are the papers uploaded here from various sources compatible with that licence?

**Comment by pinkeshbadjatiya** [comment]
@nisargjhaveri may be change it to something appropriate ?

**Comment by nisargjhaveri** [comment]
I think we should just put the links to papers, and not upload papers here.

And also change the licence to Creative Commons, for the presentations we have, as GPL is more suited for code and the Creative Commons licence works well with this kind of content.

**Comment by pinkeshbadjatiya** [comment]
done!
